[options]
admin_passwd = 123456
addons_path =   C:\Users\LENOVO\Downloads\ODOO\odoo-15.0\odoo\addons,
                C:\Users\LENOVO\Downloads\ODOO\odoo-15.0\addons,
                C:\Users\LENOVO\Downloads\ODOO\odoo-15.0\custom_addons
# db_name = odoo_education_management
# dbfilter = odoo_education_management
csv_internal_sep = ,
logfile = C:\Users\LENOVO\Downloads\ODOO\odoo-15.0\log\odoo.log
limit_memory_hard = 1395864371
limit_memory_soft = 572662306
limit_request = 8196
limit_time_cpu = 60
limit_time_real = 170
http_port = 8071
longpolling_port = 8072
proxy_mode = False
pidfile = False
import_partial =
unaccent = False
pg_path= C:\Program Files\PostgreSQL\17\bin

db_host= localhost
db_port= 5432
db_user= odoo15__2022
db_password= 123456
